# Generated by Django 3.0.4 on 2020-03-29 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist_data',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 19, 6, 31, 433249, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='todolist_data',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
