# Generated by Django 3.0.4 on 2020-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200329_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist_data',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
