# Generated by Django 3.0.4 on 2020-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_todolist_data_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist_data',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
