# Generated by Django 3.0.4 on 2020-03-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList_data',
        ),
    ]
